FROM node:20.10.0-alpine

WORKDIR /usr/src/app

COPY ./frontend/*.json .

RUN npm ci

COPY ./frontend .

RUN npm run build
RUN npm install react-scripts@3.4.1 -g

ENV NODE_ENV production
ENV PORT 3000

EXPOSE 3000

CMD ["npm", "start"]