FROM node:20.10.0-alpine

WORKDIR /usr/src/app

COPY ./frontend/*.json .

RUN npm config set cache /usr/src --global
RUN npm pkg delete scripts.prepare
RUN npm ci

COPY ./frontend/ .

RUN npm run build --production
RUN npm install -g serve

ENV NODE_ENV production
ENV PORT 3000

EXPOSE 3000

CMD serve -s build